/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.ActWebApiModelsAddress;
import com.act.client.swagger.model.SystemObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * The person who is designated for giving information or being a representative for an organization.
 */
@ApiModel(description = "The person who is designated for giving information or being a representative for an organization.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsContactsContact {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("idStatus")
  private String idStatus = null;

  @JsonProperty("isUser")
  private Boolean isUser = null;

  @JsonProperty("company")
  private String company = null;

  @JsonProperty("department")
  private String department = null;

  @JsonProperty("companyID")
  private String companyID = null;

  @JsonProperty("contactType")
  private String contactType = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("lastResults")
  private String lastResults = null;

  @JsonProperty("messengerID")
  private String messengerID = null;

  @JsonProperty("middleName")
  private String middleName = null;

  @JsonProperty("nameSuffix")
  private String nameSuffix = null;

  @JsonProperty("namePrefix")
  private String namePrefix = null;

  @JsonProperty("fullName")
  private String fullName = null;

  @JsonProperty("referredBy")
  private String referredBy = null;

  @JsonProperty("salutation")
  private String salutation = null;

  @JsonProperty("jobTitle")
  private String jobTitle = null;

  @JsonProperty("emailAddress")
  private String emailAddress = null;

  @JsonProperty("altEmailAddress")
  private String altEmailAddress = null;

  @JsonProperty("personalEmailAddress")
  private String personalEmailAddress = null;

  @JsonProperty("businessPhone")
  private String businessPhone = null;

  @JsonProperty("businessExtension")
  private String businessExtension = null;

  @JsonProperty("mobilePhone")
  private String mobilePhone = null;

  @JsonProperty("mobileExtension")
  private String mobileExtension = null;

  @JsonProperty("homePhone")
  private String homePhone = null;

  @JsonProperty("homeExtension")
  private String homeExtension = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("birthday")
  private String birthday = null;

  @JsonProperty("businessAddress")
  private ActWebApiModelsAddress businessAddress = null;

  @JsonProperty("homeAddress")
  private ActWebApiModelsAddress homeAddress = null;

  @JsonProperty("pagerPhone")
  private String pagerPhone = null;

  @JsonProperty("pagerExtension")
  private String pagerExtension = null;

  @JsonProperty("faxPhone")
  private String faxPhone = null;

  @JsonProperty("faxExtension")
  private String faxExtension = null;

  @JsonProperty("alternatePhone")
  private String alternatePhone = null;

  @JsonProperty("alternateExtension")
  private String alternateExtension = null;

  @JsonProperty("customFields")
  private Map<String, SystemObject> customFields = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("edited")
  private OffsetDateTime edited = null;

  @JsonProperty("editedBy")
  private String editedBy = null;

  @JsonProperty("recordOwner")
  private String recordOwner = null;

  public ActWebApiModelsContactsContact id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier (id) for this contact.
   * @return id
  **/
  @ApiModelProperty(value = "The unique identifier (id) for this contact.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsContactsContact idStatus(String idStatus) {
    this.idStatus = idStatus;
    return this;
  }

   /**
   * The relative social or professional position of an individual within a group or organization.
   * @return idStatus
  **/
  @ApiModelProperty(value = "The relative social or professional position of an individual within a group or organization.")
  public String getIdStatus() {
    return idStatus;
  }

  public void setIdStatus(String idStatus) {
    this.idStatus = idStatus;
  }

  public ActWebApiModelsContactsContact isUser(Boolean isUser) {
    this.isUser = isUser;
    return this;
  }

   /**
   * An indicator if this contact is also a user within the system.
   * @return isUser
  **/
  @ApiModelProperty(value = "An indicator if this contact is also a user within the system.")
  public Boolean isIsUser() {
    return isUser;
  }

  public void setIsUser(Boolean isUser) {
    this.isUser = isUser;
  }

  public ActWebApiModelsContactsContact company(String company) {
    this.company = company;
    return this;
  }

   /**
   * The organization that this contact is associated with.
   * @return company
  **/
  @ApiModelProperty(value = "The organization that this contact is associated with.")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public ActWebApiModelsContactsContact department(String department) {
    this.department = department;
    return this;
  }

   /**
   * An area of special expertise or responsibility.
   * @return department
  **/
  @ApiModelProperty(value = "An area of special expertise or responsibility.")
  public String getDepartment() {
    return department;
  }

  public void setDepartment(String department) {
    this.department = department;
  }

  public ActWebApiModelsContactsContact companyID(String companyID) {
    this.companyID = companyID;
    return this;
  }

   /**
   * The unique identifier (companyID) for a given companies.
   * @return companyID
  **/
  @ApiModelProperty(value = "The unique identifier (companyID) for a given companies.")
  public String getCompanyID() {
    return companyID;
  }

  public void setCompanyID(String companyID) {
    this.companyID = companyID;
  }

  public ActWebApiModelsContactsContact contactType(String contactType) {
    this.contactType = contactType;
    return this;
  }

   /**
   * The type of contact: Contact, Secondary, or User.
   * @return contactType
  **/
  @ApiModelProperty(value = "The type of contact: Contact, Secondary, or User.")
  public String getContactType() {
    return contactType;
  }

  public void setContactType(String contactType) {
    this.contactType = contactType;
  }

  public ActWebApiModelsContactsContact firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * A personal given name.
   * @return firstName
  **/
  @ApiModelProperty(value = "A personal given name.")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public ActWebApiModelsContactsContact lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * The family name or surname.
   * @return lastName
  **/
  @ApiModelProperty(value = "The family name or surname.")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public ActWebApiModelsContactsContact lastResults(String lastResults) {
    this.lastResults = lastResults;
    return this;
  }

   /**
   * Identifies last communication or action with a contact.
   * @return lastResults
  **/
  @ApiModelProperty(value = "Identifies last communication or action with a contact.")
  public String getLastResults() {
    return lastResults;
  }

  public void setLastResults(String lastResults) {
    this.lastResults = lastResults;
  }

  public ActWebApiModelsContactsContact messengerID(String messengerID) {
    this.messengerID = messengerID;
    return this;
  }

   /**
   * An online identifier alias.
   * @return messengerID
  **/
  @ApiModelProperty(value = "An online identifier alias.")
  public String getMessengerID() {
    return messengerID;
  }

  public void setMessengerID(String messengerID) {
    this.messengerID = messengerID;
  }

  public ActWebApiModelsContactsContact middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * A name between one&#39;s first name and surname.
   * @return middleName
  **/
  @ApiModelProperty(value = "A name between one's first name and surname.")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public ActWebApiModelsContactsContact nameSuffix(String nameSuffix) {
    this.nameSuffix = nameSuffix;
    return this;
  }

   /**
   * Provides additional information about the person that identifies an individual position, educational degree, accreditation, orffice, or honors.
   * @return nameSuffix
  **/
  @ApiModelProperty(value = "Provides additional information about the person that identifies an individual position, educational degree, accreditation, orffice, or honors.")
  public String getNameSuffix() {
    return nameSuffix;
  }

  public void setNameSuffix(String nameSuffix) {
    this.nameSuffix = nameSuffix;
  }

  public ActWebApiModelsContactsContact namePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
    return this;
  }

   /**
   * A patronymic prefix.
   * @return namePrefix
  **/
  @ApiModelProperty(value = "A patronymic prefix.")
  public String getNamePrefix() {
    return namePrefix;
  }

  public void setNamePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
  }

  public ActWebApiModelsContactsContact fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * The first name, any middle names, and surname of a contact.  This may also include name prefixes and sufixes that are defined within Act!
   * @return fullName
  **/
  @ApiModelProperty(value = "The first name, any middle names, and surname of a contact.  This may also include name prefixes and sufixes that are defined within Act!")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public ActWebApiModelsContactsContact referredBy(String referredBy) {
    this.referredBy = referredBy;
    return this;
  }

   /**
   * Indiciates how this contact came about.
   * @return referredBy
  **/
  @ApiModelProperty(value = "Indiciates how this contact came about.")
  public String getReferredBy() {
    return referredBy;
  }

  public void setReferredBy(String referredBy) {
    this.referredBy = referredBy;
  }

  public ActWebApiModelsContactsContact salutation(String salutation) {
    this.salutation = salutation;
    return this;
  }

   /**
   * A gesture or utterance made as a greeting or acknowledgment.
   * @return salutation
  **/
  @ApiModelProperty(value = "A gesture or utterance made as a greeting or acknowledgment.")
  public String getSalutation() {
    return salutation;
  }

  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  public ActWebApiModelsContactsContact jobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
    return this;
  }

   /**
   * The title or position this contact holds.
   * @return jobTitle
  **/
  @ApiModelProperty(value = "The title or position this contact holds.")
  public String getJobTitle() {
    return jobTitle;
  }

  public void setJobTitle(String jobTitle) {
    this.jobTitle = jobTitle;
  }

  public ActWebApiModelsContactsContact emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * A unique electronic address that an individual can be contacted.
   * @return emailAddress
  **/
  @ApiModelProperty(value = "A unique electronic address that an individual can be contacted.")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public ActWebApiModelsContactsContact altEmailAddress(String altEmailAddress) {
    this.altEmailAddress = altEmailAddress;
    return this;
  }

   /**
   * A unique electronic address that an individual can be contacted.
   * @return altEmailAddress
  **/
  @ApiModelProperty(value = "A unique electronic address that an individual can be contacted.")
  public String getAltEmailAddress() {
    return altEmailAddress;
  }

  public void setAltEmailAddress(String altEmailAddress) {
    this.altEmailAddress = altEmailAddress;
  }

  public ActWebApiModelsContactsContact personalEmailAddress(String personalEmailAddress) {
    this.personalEmailAddress = personalEmailAddress;
    return this;
  }

   /**
   * A unique electronic address that an individual can be contacted.
   * @return personalEmailAddress
  **/
  @ApiModelProperty(value = "A unique electronic address that an individual can be contacted.")
  public String getPersonalEmailAddress() {
    return personalEmailAddress;
  }

  public void setPersonalEmailAddress(String personalEmailAddress) {
    this.personalEmailAddress = personalEmailAddress;
  }

  public ActWebApiModelsContactsContact businessPhone(String businessPhone) {
    this.businessPhone = businessPhone;
    return this;
  }

   /**
   * The contact&#39;s business phone number.
   * @return businessPhone
  **/
  @ApiModelProperty(value = "The contact's business phone number.")
  public String getBusinessPhone() {
    return businessPhone;
  }

  public void setBusinessPhone(String businessPhone) {
    this.businessPhone = businessPhone;
  }

  public ActWebApiModelsContactsContact businessExtension(String businessExtension) {
    this.businessExtension = businessExtension;
    return this;
  }

   /**
   * The contact&#39;s business phone number extension.
   * @return businessExtension
  **/
  @ApiModelProperty(value = "The contact's business phone number extension.")
  public String getBusinessExtension() {
    return businessExtension;
  }

  public void setBusinessExtension(String businessExtension) {
    this.businessExtension = businessExtension;
  }

  public ActWebApiModelsContactsContact mobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
    return this;
  }

   /**
   * The contact&#39;s mobile phone number.
   * @return mobilePhone
  **/
  @ApiModelProperty(value = "The contact's mobile phone number.")
  public String getMobilePhone() {
    return mobilePhone;
  }

  public void setMobilePhone(String mobilePhone) {
    this.mobilePhone = mobilePhone;
  }

  public ActWebApiModelsContactsContact mobileExtension(String mobileExtension) {
    this.mobileExtension = mobileExtension;
    return this;
  }

   /**
   * The contact&#39;s mobile phone extension.
   * @return mobileExtension
  **/
  @ApiModelProperty(value = "The contact's mobile phone extension.")
  public String getMobileExtension() {
    return mobileExtension;
  }

  public void setMobileExtension(String mobileExtension) {
    this.mobileExtension = mobileExtension;
  }

  public ActWebApiModelsContactsContact homePhone(String homePhone) {
    this.homePhone = homePhone;
    return this;
  }

   /**
   * The contact&#39;s home phone number.
   * @return homePhone
  **/
  @ApiModelProperty(value = "The contact's home phone number.")
  public String getHomePhone() {
    return homePhone;
  }

  public void setHomePhone(String homePhone) {
    this.homePhone = homePhone;
  }

  public ActWebApiModelsContactsContact homeExtension(String homeExtension) {
    this.homeExtension = homeExtension;
    return this;
  }

   /**
   * The contact&#39;s home phone extension.
   * @return homeExtension
  **/
  @ApiModelProperty(value = "The contact's home phone extension.")
  public String getHomeExtension() {
    return homeExtension;
  }

  public void setHomeExtension(String homeExtension) {
    this.homeExtension = homeExtension;
  }

  public ActWebApiModelsContactsContact website(String website) {
    this.website = website;
    return this;
  }

   /**
   * The contact&#39;s web site.
   * @return website
  **/
  @ApiModelProperty(value = "The contact's web site.")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public ActWebApiModelsContactsContact birthday(String birthday) {
    this.birthday = birthday;
    return this;
  }

   /**
   * The anniversary of the day on which a person was born.
   * @return birthday
  **/
  @ApiModelProperty(value = "The anniversary of the day on which a person was born.")
  public String getBirthday() {
    return birthday;
  }

  public void setBirthday(String birthday) {
    this.birthday = birthday;
  }

  public ActWebApiModelsContactsContact businessAddress(ActWebApiModelsAddress businessAddress) {
    this.businessAddress = businessAddress;
    return this;
  }

   /**
   * The contact&#39;s business address.
   * @return businessAddress
  **/
  @ApiModelProperty(value = "The contact's business address.")
  public ActWebApiModelsAddress getBusinessAddress() {
    return businessAddress;
  }

  public void setBusinessAddress(ActWebApiModelsAddress businessAddress) {
    this.businessAddress = businessAddress;
  }

  public ActWebApiModelsContactsContact homeAddress(ActWebApiModelsAddress homeAddress) {
    this.homeAddress = homeAddress;
    return this;
  }

   /**
   * The contact&#39;s home address.
   * @return homeAddress
  **/
  @ApiModelProperty(value = "The contact's home address.")
  public ActWebApiModelsAddress getHomeAddress() {
    return homeAddress;
  }

  public void setHomeAddress(ActWebApiModelsAddress homeAddress) {
    this.homeAddress = homeAddress;
  }

  public ActWebApiModelsContactsContact pagerPhone(String pagerPhone) {
    this.pagerPhone = pagerPhone;
    return this;
  }

   /**
   * The contact&#39;s pager phone number.
   * @return pagerPhone
  **/
  @ApiModelProperty(value = "The contact's pager phone number.")
  public String getPagerPhone() {
    return pagerPhone;
  }

  public void setPagerPhone(String pagerPhone) {
    this.pagerPhone = pagerPhone;
  }

  public ActWebApiModelsContactsContact pagerExtension(String pagerExtension) {
    this.pagerExtension = pagerExtension;
    return this;
  }

   /**
   * The contact&#39;s pager phone number extension
   * @return pagerExtension
  **/
  @ApiModelProperty(value = "The contact's pager phone number extension")
  public String getPagerExtension() {
    return pagerExtension;
  }

  public void setPagerExtension(String pagerExtension) {
    this.pagerExtension = pagerExtension;
  }

  public ActWebApiModelsContactsContact faxPhone(String faxPhone) {
    this.faxPhone = faxPhone;
    return this;
  }

   /**
   * The contact&#39;s fax phone number.
   * @return faxPhone
  **/
  @ApiModelProperty(value = "The contact's fax phone number.")
  public String getFaxPhone() {
    return faxPhone;
  }

  public void setFaxPhone(String faxPhone) {
    this.faxPhone = faxPhone;
  }

  public ActWebApiModelsContactsContact faxExtension(String faxExtension) {
    this.faxExtension = faxExtension;
    return this;
  }

   /**
   * The contact&#39;s fax phone number extension.
   * @return faxExtension
  **/
  @ApiModelProperty(value = "The contact's fax phone number extension.")
  public String getFaxExtension() {
    return faxExtension;
  }

  public void setFaxExtension(String faxExtension) {
    this.faxExtension = faxExtension;
  }

  public ActWebApiModelsContactsContact alternatePhone(String alternatePhone) {
    this.alternatePhone = alternatePhone;
    return this;
  }

   /**
   * The contact&#39;s alternate phone number.
   * @return alternatePhone
  **/
  @ApiModelProperty(value = "The contact's alternate phone number.")
  public String getAlternatePhone() {
    return alternatePhone;
  }

  public void setAlternatePhone(String alternatePhone) {
    this.alternatePhone = alternatePhone;
  }

  public ActWebApiModelsContactsContact alternateExtension(String alternateExtension) {
    this.alternateExtension = alternateExtension;
    return this;
  }

   /**
   * The contact&#39;s alternate phone number extension.
   * @return alternateExtension
  **/
  @ApiModelProperty(value = "The contact's alternate phone number extension.")
  public String getAlternateExtension() {
    return alternateExtension;
  }

  public void setAlternateExtension(String alternateExtension) {
    this.alternateExtension = alternateExtension;
  }

  public ActWebApiModelsContactsContact customFields(Map<String, SystemObject> customFields) {
    this.customFields = customFields;
    return this;
  }

  public ActWebApiModelsContactsContact putCustomFieldsItem(String key, SystemObject customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<String, SystemObject>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @ApiModelProperty(value = "")
  public Map<String, SystemObject> getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Map<String, SystemObject> customFields) {
    this.customFields = customFields;
  }

  public ActWebApiModelsContactsContact created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ActWebApiModelsContactsContact edited(OffsetDateTime edited) {
    this.edited = edited;
    return this;
  }

   /**
   * Get edited
   * @return edited
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEdited() {
    return edited;
  }

  public void setEdited(OffsetDateTime edited) {
    this.edited = edited;
  }

  public ActWebApiModelsContactsContact editedBy(String editedBy) {
    this.editedBy = editedBy;
    return this;
  }

   /**
   * Get editedBy
   * @return editedBy
  **/
  @ApiModelProperty(value = "")
  public String getEditedBy() {
    return editedBy;
  }

  public void setEditedBy(String editedBy) {
    this.editedBy = editedBy;
  }

  public ActWebApiModelsContactsContact recordOwner(String recordOwner) {
    this.recordOwner = recordOwner;
    return this;
  }

   /**
   * Get recordOwner
   * @return recordOwner
  **/
  @ApiModelProperty(value = "")
  public String getRecordOwner() {
    return recordOwner;
  }

  public void setRecordOwner(String recordOwner) {
    this.recordOwner = recordOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsContactsContact actWebApiModelsContactsContact = (ActWebApiModelsContactsContact) o;
    return Objects.equals(this.id, actWebApiModelsContactsContact.id) &&
        Objects.equals(this.idStatus, actWebApiModelsContactsContact.idStatus) &&
        Objects.equals(this.isUser, actWebApiModelsContactsContact.isUser) &&
        Objects.equals(this.company, actWebApiModelsContactsContact.company) &&
        Objects.equals(this.department, actWebApiModelsContactsContact.department) &&
        Objects.equals(this.companyID, actWebApiModelsContactsContact.companyID) &&
        Objects.equals(this.contactType, actWebApiModelsContactsContact.contactType) &&
        Objects.equals(this.firstName, actWebApiModelsContactsContact.firstName) &&
        Objects.equals(this.lastName, actWebApiModelsContactsContact.lastName) &&
        Objects.equals(this.lastResults, actWebApiModelsContactsContact.lastResults) &&
        Objects.equals(this.messengerID, actWebApiModelsContactsContact.messengerID) &&
        Objects.equals(this.middleName, actWebApiModelsContactsContact.middleName) &&
        Objects.equals(this.nameSuffix, actWebApiModelsContactsContact.nameSuffix) &&
        Objects.equals(this.namePrefix, actWebApiModelsContactsContact.namePrefix) &&
        Objects.equals(this.fullName, actWebApiModelsContactsContact.fullName) &&
        Objects.equals(this.referredBy, actWebApiModelsContactsContact.referredBy) &&
        Objects.equals(this.salutation, actWebApiModelsContactsContact.salutation) &&
        Objects.equals(this.jobTitle, actWebApiModelsContactsContact.jobTitle) &&
        Objects.equals(this.emailAddress, actWebApiModelsContactsContact.emailAddress) &&
        Objects.equals(this.altEmailAddress, actWebApiModelsContactsContact.altEmailAddress) &&
        Objects.equals(this.personalEmailAddress, actWebApiModelsContactsContact.personalEmailAddress) &&
        Objects.equals(this.businessPhone, actWebApiModelsContactsContact.businessPhone) &&
        Objects.equals(this.businessExtension, actWebApiModelsContactsContact.businessExtension) &&
        Objects.equals(this.mobilePhone, actWebApiModelsContactsContact.mobilePhone) &&
        Objects.equals(this.mobileExtension, actWebApiModelsContactsContact.mobileExtension) &&
        Objects.equals(this.homePhone, actWebApiModelsContactsContact.homePhone) &&
        Objects.equals(this.homeExtension, actWebApiModelsContactsContact.homeExtension) &&
        Objects.equals(this.website, actWebApiModelsContactsContact.website) &&
        Objects.equals(this.birthday, actWebApiModelsContactsContact.birthday) &&
        Objects.equals(this.businessAddress, actWebApiModelsContactsContact.businessAddress) &&
        Objects.equals(this.homeAddress, actWebApiModelsContactsContact.homeAddress) &&
        Objects.equals(this.pagerPhone, actWebApiModelsContactsContact.pagerPhone) &&
        Objects.equals(this.pagerExtension, actWebApiModelsContactsContact.pagerExtension) &&
        Objects.equals(this.faxPhone, actWebApiModelsContactsContact.faxPhone) &&
        Objects.equals(this.faxExtension, actWebApiModelsContactsContact.faxExtension) &&
        Objects.equals(this.alternatePhone, actWebApiModelsContactsContact.alternatePhone) &&
        Objects.equals(this.alternateExtension, actWebApiModelsContactsContact.alternateExtension) &&
        Objects.equals(this.customFields, actWebApiModelsContactsContact.customFields) &&
        Objects.equals(this.created, actWebApiModelsContactsContact.created) &&
        Objects.equals(this.edited, actWebApiModelsContactsContact.edited) &&
        Objects.equals(this.editedBy, actWebApiModelsContactsContact.editedBy) &&
        Objects.equals(this.recordOwner, actWebApiModelsContactsContact.recordOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, idStatus, isUser, company, department, companyID, contactType, firstName, lastName, lastResults, messengerID, middleName, nameSuffix, namePrefix, fullName, referredBy, salutation, jobTitle, emailAddress, altEmailAddress, personalEmailAddress, businessPhone, businessExtension, mobilePhone, mobileExtension, homePhone, homeExtension, website, birthday, businessAddress, homeAddress, pagerPhone, pagerExtension, faxPhone, faxExtension, alternatePhone, alternateExtension, customFields, created, edited, editedBy, recordOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsContactsContact {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    idStatus: ").append(toIndentedString(idStatus)).append("\n");
    sb.append("    isUser: ").append(toIndentedString(isUser)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    companyID: ").append(toIndentedString(companyID)).append("\n");
    sb.append("    contactType: ").append(toIndentedString(contactType)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    lastResults: ").append(toIndentedString(lastResults)).append("\n");
    sb.append("    messengerID: ").append(toIndentedString(messengerID)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    nameSuffix: ").append(toIndentedString(nameSuffix)).append("\n");
    sb.append("    namePrefix: ").append(toIndentedString(namePrefix)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    referredBy: ").append(toIndentedString(referredBy)).append("\n");
    sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
    sb.append("    jobTitle: ").append(toIndentedString(jobTitle)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    altEmailAddress: ").append(toIndentedString(altEmailAddress)).append("\n");
    sb.append("    personalEmailAddress: ").append(toIndentedString(personalEmailAddress)).append("\n");
    sb.append("    businessPhone: ").append(toIndentedString(businessPhone)).append("\n");
    sb.append("    businessExtension: ").append(toIndentedString(businessExtension)).append("\n");
    sb.append("    mobilePhone: ").append(toIndentedString(mobilePhone)).append("\n");
    sb.append("    mobileExtension: ").append(toIndentedString(mobileExtension)).append("\n");
    sb.append("    homePhone: ").append(toIndentedString(homePhone)).append("\n");
    sb.append("    homeExtension: ").append(toIndentedString(homeExtension)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("    businessAddress: ").append(toIndentedString(businessAddress)).append("\n");
    sb.append("    homeAddress: ").append(toIndentedString(homeAddress)).append("\n");
    sb.append("    pagerPhone: ").append(toIndentedString(pagerPhone)).append("\n");
    sb.append("    pagerExtension: ").append(toIndentedString(pagerExtension)).append("\n");
    sb.append("    faxPhone: ").append(toIndentedString(faxPhone)).append("\n");
    sb.append("    faxExtension: ").append(toIndentedString(faxExtension)).append("\n");
    sb.append("    alternatePhone: ").append(toIndentedString(alternatePhone)).append("\n");
    sb.append("    alternateExtension: ").append(toIndentedString(alternateExtension)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    editedBy: ").append(toIndentedString(editedBy)).append("\n");
    sb.append("    recordOwner: ").append(toIndentedString(recordOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

