/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsMetaDataSchemaPickListInfo {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("isLimitToList")
  private Boolean isLimitToList = null;

  @JsonProperty("isMultiSelect")
  private Boolean isMultiSelect = null;

  @JsonProperty("isTypeAhead")
  private Boolean isTypeAhead = null;

  @JsonProperty("showDescription")
  private Boolean showDescription = null;

  public ActWebApiModelsMetaDataSchemaPickListInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo isLimitToList(Boolean isLimitToList) {
    this.isLimitToList = isLimitToList;
    return this;
  }

   /**
   * 
   * @return isLimitToList
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsLimitToList() {
    return isLimitToList;
  }

  public void setIsLimitToList(Boolean isLimitToList) {
    this.isLimitToList = isLimitToList;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo isMultiSelect(Boolean isMultiSelect) {
    this.isMultiSelect = isMultiSelect;
    return this;
  }

   /**
   * 
   * @return isMultiSelect
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsMultiSelect() {
    return isMultiSelect;
  }

  public void setIsMultiSelect(Boolean isMultiSelect) {
    this.isMultiSelect = isMultiSelect;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo isTypeAhead(Boolean isTypeAhead) {
    this.isTypeAhead = isTypeAhead;
    return this;
  }

   /**
   * 
   * @return isTypeAhead
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsTypeAhead() {
    return isTypeAhead;
  }

  public void setIsTypeAhead(Boolean isTypeAhead) {
    this.isTypeAhead = isTypeAhead;
  }

  public ActWebApiModelsMetaDataSchemaPickListInfo showDescription(Boolean showDescription) {
    this.showDescription = showDescription;
    return this;
  }

   /**
   * 
   * @return showDescription
  **/
  @ApiModelProperty(value = "")
  public Boolean isShowDescription() {
    return showDescription;
  }

  public void setShowDescription(Boolean showDescription) {
    this.showDescription = showDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsMetaDataSchemaPickListInfo actWebApiModelsMetaDataSchemaPickListInfo = (ActWebApiModelsMetaDataSchemaPickListInfo) o;
    return Objects.equals(this.id, actWebApiModelsMetaDataSchemaPickListInfo.id) &&
        Objects.equals(this.name, actWebApiModelsMetaDataSchemaPickListInfo.name) &&
        Objects.equals(this.description, actWebApiModelsMetaDataSchemaPickListInfo.description) &&
        Objects.equals(this.isLimitToList, actWebApiModelsMetaDataSchemaPickListInfo.isLimitToList) &&
        Objects.equals(this.isMultiSelect, actWebApiModelsMetaDataSchemaPickListInfo.isMultiSelect) &&
        Objects.equals(this.isTypeAhead, actWebApiModelsMetaDataSchemaPickListInfo.isTypeAhead) &&
        Objects.equals(this.showDescription, actWebApiModelsMetaDataSchemaPickListInfo.showDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, isLimitToList, isMultiSelect, isTypeAhead, showDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsMetaDataSchemaPickListInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isLimitToList: ").append(toIndentedString(isLimitToList)).append("\n");
    sb.append("    isMultiSelect: ").append(toIndentedString(isMultiSelect)).append("\n");
    sb.append("    isTypeAhead: ").append(toIndentedString(isTypeAhead)).append("\n");
    sb.append("    showDescription: ").append(toIndentedString(showDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

