/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * Provides properties information about attachments.
 */
@ApiModel(description = "Provides properties information about attachments.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsAttachmentsAttachment {
  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("fileExtension")
  private String fileExtension = null;

  @JsonProperty("fileName")
  private String fileName = null;

  @JsonProperty("fileSize")
  private Long fileSize = null;

  @JsonProperty("fileSizeDisplay")
  private String fileSizeDisplay = null;

  @JsonProperty("fileType")
  private String fileType = null;

  @JsonProperty("lastModified")
  private OffsetDateTime lastModified = null;

  @JsonProperty("personal")
  private Boolean personal = null;

  public ActWebApiModelsAttachmentsAttachment displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Gets presentation name of the attachment.
   * @return displayName
  **/
  @ApiModelProperty(value = "Gets presentation name of the attachment.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ActWebApiModelsAttachmentsAttachment fileExtension(String fileExtension) {
    this.fileExtension = fileExtension;
    return this;
  }

   /**
   * Gets the extension of the Attachment
   * @return fileExtension
  **/
  @ApiModelProperty(value = "Gets the extension of the Attachment")
  public String getFileExtension() {
    return fileExtension;
  }

  public void setFileExtension(String fileExtension) {
    this.fileExtension = fileExtension;
  }

  public ActWebApiModelsAttachmentsAttachment fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Gets a string representing the directory&#39;s full path.
   * @return fileName
  **/
  @ApiModelProperty(value = "Gets a string representing the directory's full path.")
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public ActWebApiModelsAttachmentsAttachment fileSize(Long fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Gets the size (bytes) of the attachments.
   * @return fileSize
  **/
  @ApiModelProperty(value = "Gets the size (bytes) of the attachments.")
  public Long getFileSize() {
    return fileSize;
  }

  public void setFileSize(Long fileSize) {
    this.fileSize = fileSize;
  }

  public ActWebApiModelsAttachmentsAttachment fileSizeDisplay(String fileSizeDisplay) {
    this.fileSizeDisplay = fileSizeDisplay;
    return this;
  }

   /**
   * Gets the displayable text representation of the attachment
   * @return fileSizeDisplay
  **/
  @ApiModelProperty(value = "Gets the displayable text representation of the attachment")
  public String getFileSizeDisplay() {
    return fileSizeDisplay;
  }

  public void setFileSizeDisplay(String fileSizeDisplay) {
    this.fileSizeDisplay = fileSizeDisplay;
  }

  public ActWebApiModelsAttachmentsAttachment fileType(String fileType) {
    this.fileType = fileType;
    return this;
  }

   /**
   * Gets the registered system file type name of the attachment
   * @return fileType
  **/
  @ApiModelProperty(value = "Gets the registered system file type name of the attachment")
  public String getFileType() {
    return fileType;
  }

  public void setFileType(String fileType) {
    this.fileType = fileType;
  }

  public ActWebApiModelsAttachmentsAttachment lastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Gets the last modified date of the attachment
   * @return lastModified
  **/
  @ApiModelProperty(value = "Gets the last modified date of the attachment")
  public OffsetDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public ActWebApiModelsAttachmentsAttachment personal(Boolean personal) {
    this.personal = personal;
    return this;
  }

   /**
   * Indicates whether the attachment is bound for the personal suppplemental files or the workgroup supplemental files.
   * @return personal
  **/
  @ApiModelProperty(value = "Indicates whether the attachment is bound for the personal suppplemental files or the workgroup supplemental files.")
  public Boolean isPersonal() {
    return personal;
  }

  public void setPersonal(Boolean personal) {
    this.personal = personal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsAttachmentsAttachment actWebApiModelsAttachmentsAttachment = (ActWebApiModelsAttachmentsAttachment) o;
    return Objects.equals(this.displayName, actWebApiModelsAttachmentsAttachment.displayName) &&
        Objects.equals(this.fileExtension, actWebApiModelsAttachmentsAttachment.fileExtension) &&
        Objects.equals(this.fileName, actWebApiModelsAttachmentsAttachment.fileName) &&
        Objects.equals(this.fileSize, actWebApiModelsAttachmentsAttachment.fileSize) &&
        Objects.equals(this.fileSizeDisplay, actWebApiModelsAttachmentsAttachment.fileSizeDisplay) &&
        Objects.equals(this.fileType, actWebApiModelsAttachmentsAttachment.fileType) &&
        Objects.equals(this.lastModified, actWebApiModelsAttachmentsAttachment.lastModified) &&
        Objects.equals(this.personal, actWebApiModelsAttachmentsAttachment.personal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, fileExtension, fileName, fileSize, fileSizeDisplay, fileType, lastModified, personal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsAttachmentsAttachment {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fileExtension: ").append(toIndentedString(fileExtension)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    fileSizeDisplay: ").append(toIndentedString(fileSizeDisplay)).append("\n");
    sb.append("    fileType: ").append(toIndentedString(fileType)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    personal: ").append(toIndentedString(personal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

