/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.ActWebApiModelsOpportunitiesProcess;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A class which describes the stage state of a particular {act.web.api.models.Opportunities.Opportunity} object.
 */
@ApiModel(description = "A class which describes the stage state of a particular {act.web.api.models.Opportunities.Opportunity} object.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsOpportunitiesStage {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("number")
  private Integer number = null;

  @JsonProperty("probability")
  private Integer probability = null;

  @JsonProperty("process")
  private ActWebApiModelsOpportunitiesProcess process = null;

  public ActWebApiModelsOpportunitiesStage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Gets the unique identifier of the stage.
   * @return id
  **/
  @ApiModelProperty(value = "Gets the unique identifier of the stage.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsOpportunitiesStage name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets/Sets the name of the stage.
   * @return name
  **/
  @ApiModelProperty(value = "Gets/Sets the name of the stage.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsOpportunitiesStage description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Gets/Sets the description of the stage.
   * @return description
  **/
  @ApiModelProperty(value = "Gets/Sets the description of the stage.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActWebApiModelsOpportunitiesStage number(Integer number) {
    this.number = number;
    return this;
  }

   /**
   * Gets/Sets the ordinal number of the stage.
   * @return number
  **/
  @ApiModelProperty(value = "Gets/Sets the ordinal number of the stage.")
  public Integer getNumber() {
    return number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  public ActWebApiModelsOpportunitiesStage probability(Integer probability) {
    this.probability = probability;
    return this;
  }

   /**
   * Gets/Sets the probability of the stage.
   * @return probability
  **/
  @ApiModelProperty(value = "Gets/Sets the probability of the stage.")
  public Integer getProbability() {
    return probability;
  }

  public void setProbability(Integer probability) {
    this.probability = probability;
  }

  public ActWebApiModelsOpportunitiesStage process(ActWebApiModelsOpportunitiesProcess process) {
    this.process = process;
    return this;
  }

   /**
   * Represents the current process for a given opportunity
   * @return process
  **/
  @ApiModelProperty(value = "Represents the current process for a given opportunity")
  public ActWebApiModelsOpportunitiesProcess getProcess() {
    return process;
  }

  public void setProcess(ActWebApiModelsOpportunitiesProcess process) {
    this.process = process;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsOpportunitiesStage actWebApiModelsOpportunitiesStage = (ActWebApiModelsOpportunitiesStage) o;
    return Objects.equals(this.id, actWebApiModelsOpportunitiesStage.id) &&
        Objects.equals(this.name, actWebApiModelsOpportunitiesStage.name) &&
        Objects.equals(this.description, actWebApiModelsOpportunitiesStage.description) &&
        Objects.equals(this.number, actWebApiModelsOpportunitiesStage.number) &&
        Objects.equals(this.probability, actWebApiModelsOpportunitiesStage.probability) &&
        Objects.equals(this.process, actWebApiModelsOpportunitiesStage.process);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, number, probability, process);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsOpportunitiesStage {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    process: ").append(toIndentedString(process)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

