/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.ActWebApiModelsAttachmentsAttachment;
import com.act.client.swagger.model.ActWebApiModelsHistoriesHistoryType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * Creates a history when clearing an activity
 */
@ApiModel(description = "Creates a history when clearing an activity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsActivitiesClearActivity {
  @JsonProperty("historyType")
  private ActWebApiModelsHistoriesHistoryType historyType = null;

  @JsonProperty("startTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("endTime")
  private OffsetDateTime endTime = null;

  @JsonProperty("includeDetailsToHistory")
  private Boolean includeDetailsToHistory = null;

  @JsonProperty("details")
  private String details = null;

  @JsonProperty("subject")
  private String subject = null;

  @JsonProperty("isPrivate")
  private Boolean isPrivate = null;

  @JsonProperty("attachment")
  private ActWebApiModelsAttachmentsAttachment attachment = null;

  public ActWebApiModelsActivitiesClearActivity historyType(ActWebApiModelsHistoriesHistoryType historyType) {
    this.historyType = historyType;
    return this;
  }

   /**
   * Provides information about the history event.
   * @return historyType
  **/
  @ApiModelProperty(value = "Provides information about the history event.")
  public ActWebApiModelsHistoriesHistoryType getHistoryType() {
    return historyType;
  }

  public void setHistoryType(ActWebApiModelsHistoriesHistoryType historyType) {
    this.historyType = historyType;
  }

  public ActWebApiModelsActivitiesClearActivity startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * The time the activity is to begin.
   * @return startTime
  **/
  @ApiModelProperty(required = true, value = "The time the activity is to begin.")
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public ActWebApiModelsActivitiesClearActivity endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * The time the activity is to end.
   * @return endTime
  **/
  @ApiModelProperty(required = true, value = "The time the activity is to end.")
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public ActWebApiModelsActivitiesClearActivity includeDetailsToHistory(Boolean includeDetailsToHistory) {
    this.includeDetailsToHistory = includeDetailsToHistory;
    return this;
  }

   /**
   * Indicates that shared history includes details.
   * @return includeDetailsToHistory
  **/
  @ApiModelProperty(value = "Indicates that shared history includes details.")
  public Boolean isIncludeDetailsToHistory() {
    return includeDetailsToHistory;
  }

  public void setIncludeDetailsToHistory(Boolean includeDetailsToHistory) {
    this.includeDetailsToHistory = includeDetailsToHistory;
  }

  public ActWebApiModelsActivitiesClearActivity details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Additional detailed information about the activity.
   * @return details
  **/
  @ApiModelProperty(value = "Additional detailed information about the activity.")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public ActWebApiModelsActivitiesClearActivity subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * A description of the action to be completed.
   * @return subject
  **/
  @ApiModelProperty(value = "A description of the action to be completed.")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public ActWebApiModelsActivitiesClearActivity isPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Indicates elevated security that only the creator/owner has access to this activity.
   * @return isPrivate
  **/
  @ApiModelProperty(value = "Indicates elevated security that only the creator/owner has access to this activity.")
  public Boolean isIsPrivate() {
    return isPrivate;
  }

  public void setIsPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
  }

  public ActWebApiModelsActivitiesClearActivity attachment(ActWebApiModelsAttachmentsAttachment attachment) {
    this.attachment = attachment;
    return this;
  }

   /**
   * Gets the attachment referenced by this note.
   * @return attachment
  **/
  @ApiModelProperty(value = "Gets the attachment referenced by this note.")
  public ActWebApiModelsAttachmentsAttachment getAttachment() {
    return attachment;
  }

  public void setAttachment(ActWebApiModelsAttachmentsAttachment attachment) {
    this.attachment = attachment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsActivitiesClearActivity actWebApiModelsActivitiesClearActivity = (ActWebApiModelsActivitiesClearActivity) o;
    return Objects.equals(this.historyType, actWebApiModelsActivitiesClearActivity.historyType) &&
        Objects.equals(this.startTime, actWebApiModelsActivitiesClearActivity.startTime) &&
        Objects.equals(this.endTime, actWebApiModelsActivitiesClearActivity.endTime) &&
        Objects.equals(this.includeDetailsToHistory, actWebApiModelsActivitiesClearActivity.includeDetailsToHistory) &&
        Objects.equals(this.details, actWebApiModelsActivitiesClearActivity.details) &&
        Objects.equals(this.subject, actWebApiModelsActivitiesClearActivity.subject) &&
        Objects.equals(this.isPrivate, actWebApiModelsActivitiesClearActivity.isPrivate) &&
        Objects.equals(this.attachment, actWebApiModelsActivitiesClearActivity.attachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(historyType, startTime, endTime, includeDetailsToHistory, details, subject, isPrivate, attachment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsActivitiesClearActivity {\n");
    
    sb.append("    historyType: ").append(toIndentedString(historyType)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    includeDetailsToHistory: ").append(toIndentedString(includeDetailsToHistory)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

