/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsMetadataTypeCodesHistoryType {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("activityTypeID")
  private String activityTypeID = null;

  @JsonProperty("activityTypeName")
  private String activityTypeName = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("isDefault")
  private Boolean isDefault = null;

  public ActWebApiModelsMetadataTypeCodesHistoryType id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ActWebApiModelsMetadataTypeCodesHistoryType name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsMetadataTypeCodesHistoryType activityTypeID(String activityTypeID) {
    this.activityTypeID = activityTypeID;
    return this;
  }

   /**
   * 
   * @return activityTypeID
  **/
  @ApiModelProperty(value = "")
  public String getActivityTypeID() {
    return activityTypeID;
  }

  public void setActivityTypeID(String activityTypeID) {
    this.activityTypeID = activityTypeID;
  }

  public ActWebApiModelsMetadataTypeCodesHistoryType activityTypeName(String activityTypeName) {
    this.activityTypeName = activityTypeName;
    return this;
  }

   /**
   * 
   * @return activityTypeName
  **/
  @ApiModelProperty(value = "")
  public String getActivityTypeName() {
    return activityTypeName;
  }

  public void setActivityTypeName(String activityTypeName) {
    this.activityTypeName = activityTypeName;
  }

  public ActWebApiModelsMetadataTypeCodesHistoryType description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActWebApiModelsMetadataTypeCodesHistoryType isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * 
   * @return isDefault
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsMetadataTypeCodesHistoryType actWebApiModelsMetadataTypeCodesHistoryType = (ActWebApiModelsMetadataTypeCodesHistoryType) o;
    return Objects.equals(this.id, actWebApiModelsMetadataTypeCodesHistoryType.id) &&
        Objects.equals(this.name, actWebApiModelsMetadataTypeCodesHistoryType.name) &&
        Objects.equals(this.activityTypeID, actWebApiModelsMetadataTypeCodesHistoryType.activityTypeID) &&
        Objects.equals(this.activityTypeName, actWebApiModelsMetadataTypeCodesHistoryType.activityTypeName) &&
        Objects.equals(this.description, actWebApiModelsMetadataTypeCodesHistoryType.description) &&
        Objects.equals(this.isDefault, actWebApiModelsMetadataTypeCodesHistoryType.isDefault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, activityTypeID, activityTypeName, description, isDefault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsMetadataTypeCodesHistoryType {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    activityTypeID: ").append(toIndentedString(activityTypeID)).append("\n");
    sb.append("    activityTypeName: ").append(toIndentedString(activityTypeName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

