/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * Analytics Reports: Periodic Revienue arguments.
 */
@ApiModel(description = "Analytics Reports: Periodic Revienue arguments.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsAnalyticsPeriodicRevenueArgs {
  /**
   * An intervening period of time.
   */
  public enum IntervalEnum {
    DAILY("Daily"),
    
    WEEKLY("Weekly"),
    
    MONTHLY("Monthly"),
    
    QUARTERLY("Quarterly"),
    
    YEARLY("Yearly");

    private String value;

    IntervalEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static IntervalEnum fromValue(String text) {
      for (IntervalEnum b : IntervalEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("interval")
  private IntervalEnum interval = null;

  @JsonProperty("start")
  private OffsetDateTime start = null;

  @JsonProperty("end")
  private OffsetDateTime end = null;

  @JsonProperty("fiscalYearStart")
  private Integer fiscalYearStart = null;

  public ActWebApiModelsAnalyticsPeriodicRevenueArgs interval(IntervalEnum interval) {
    this.interval = interval;
    return this;
  }

   /**
   * An intervening period of time.
   * @return interval
  **/
  @ApiModelProperty(value = "An intervening period of time.")
  public IntervalEnum getInterval() {
    return interval;
  }

  public void setInterval(IntervalEnum interval) {
    this.interval = interval;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenueArgs start(OffsetDateTime start) {
    this.start = start;
    return this;
  }

   /**
   * The start date that the period requesting.
   * @return start
  **/
  @ApiModelProperty(value = "The start date that the period requesting.")
  public OffsetDateTime getStart() {
    return start;
  }

  public void setStart(OffsetDateTime start) {
    this.start = start;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenueArgs end(OffsetDateTime end) {
    this.end = end;
    return this;
  }

   /**
   * The end date that the period requesting.
   * @return end
  **/
  @ApiModelProperty(value = "The end date that the period requesting.")
  public OffsetDateTime getEnd() {
    return end;
  }

  public void setEnd(OffsetDateTime end) {
    this.end = end;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenueArgs fiscalYearStart(Integer fiscalYearStart) {
    this.fiscalYearStart = fiscalYearStart;
    return this;
  }

   /**
   * The oppourtunity products that will be evaludated to generate the revenue data.
   * @return fiscalYearStart
  **/
  @ApiModelProperty(value = "The oppourtunity products that will be evaludated to generate the revenue data.")
  public Integer getFiscalYearStart() {
    return fiscalYearStart;
  }

  public void setFiscalYearStart(Integer fiscalYearStart) {
    this.fiscalYearStart = fiscalYearStart;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsAnalyticsPeriodicRevenueArgs actWebApiModelsAnalyticsPeriodicRevenueArgs = (ActWebApiModelsAnalyticsPeriodicRevenueArgs) o;
    return Objects.equals(this.interval, actWebApiModelsAnalyticsPeriodicRevenueArgs.interval) &&
        Objects.equals(this.start, actWebApiModelsAnalyticsPeriodicRevenueArgs.start) &&
        Objects.equals(this.end, actWebApiModelsAnalyticsPeriodicRevenueArgs.end) &&
        Objects.equals(this.fiscalYearStart, actWebApiModelsAnalyticsPeriodicRevenueArgs.fiscalYearStart);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interval, start, end, fiscalYearStart);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsAnalyticsPeriodicRevenueArgs {\n");
    
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    fiscalYearStart: ").append(toIndentedString(fiscalYearStart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

