/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.SystemObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents a value item for a PickList object.
 */
@ApiModel(description = "Represents a value item for a PickList object.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsMetaDataPicklistsPickListItem {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("value")
  private SystemObject value = null;

  @JsonProperty("description")
  private String description = null;

  public ActWebApiModelsMetaDataPicklistsPickListItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Gets the unique identifier of the PickListItem object.
   * @return id
  **/
  @ApiModelProperty(value = "Gets the unique identifier of the PickListItem object.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsMetaDataPicklistsPickListItem value(SystemObject value) {
    this.value = value;
    return this;
  }

   /**
   * Gets or sets the value of the PickListItem object.
   * @return value
  **/
  @ApiModelProperty(value = "Gets or sets the value of the PickListItem object.")
  public SystemObject getValue() {
    return value;
  }

  public void setValue(SystemObject value) {
    this.value = value;
  }

  public ActWebApiModelsMetaDataPicklistsPickListItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Gets the description of the picklist item.
   * @return description
  **/
  @ApiModelProperty(value = "Gets the description of the picklist item.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsMetaDataPicklistsPickListItem actWebApiModelsMetaDataPicklistsPickListItem = (ActWebApiModelsMetaDataPicklistsPickListItem) o;
    return Objects.equals(this.id, actWebApiModelsMetaDataPicklistsPickListItem.id) &&
        Objects.equals(this.value, actWebApiModelsMetaDataPicklistsPickListItem.value) &&
        Objects.equals(this.description, actWebApiModelsMetaDataPicklistsPickListItem.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, value, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsMetaDataPicklistsPickListItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

