/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * This class describes a particular product.
 */
@ApiModel(description = "This class describes a particular product.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsProductsProduct {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("cost")
  private Double cost = null;

  @JsonProperty("createDate")
  private OffsetDateTime createDate = null;

  @JsonProperty("editDate")
  private OffsetDateTime editDate = null;

  @JsonProperty("itemNumber")
  private String itemNumber = null;

  @JsonProperty("price")
  private Double price = null;

  public ActWebApiModelsProductsProduct id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier (id) for a given product.
   * @return id
  **/
  @ApiModelProperty(value = "A unique identifier (id) for a given product.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsProductsProduct name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the product.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the product.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsProductsProduct cost(Double cost) {
    this.cost = cost;
    return this;
  }

   /**
   * The cost of the product.
   * @return cost
  **/
  @ApiModelProperty(value = "The cost of the product.")
  public Double getCost() {
    return cost;
  }

  public void setCost(Double cost) {
    this.cost = cost;
  }

  public ActWebApiModelsProductsProduct createDate(OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

   /**
   * The date that the product was created.
   * @return createDate
  **/
  @ApiModelProperty(value = "The date that the product was created.")
  public OffsetDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }

  public ActWebApiModelsProductsProduct editDate(OffsetDateTime editDate) {
    this.editDate = editDate;
    return this;
  }

   /**
   * The date that the opportunity product was lasted modified.
   * @return editDate
  **/
  @ApiModelProperty(value = "The date that the opportunity product was lasted modified.")
  public OffsetDateTime getEditDate() {
    return editDate;
  }

  public void setEditDate(OffsetDateTime editDate) {
    this.editDate = editDate;
  }

  public ActWebApiModelsProductsProduct itemNumber(String itemNumber) {
    this.itemNumber = itemNumber;
    return this;
  }

   /**
   * A item number assigned to this opportunity product.
   * @return itemNumber
  **/
  @ApiModelProperty(value = "A item number assigned to this opportunity product.")
  public String getItemNumber() {
    return itemNumber;
  }

  public void setItemNumber(String itemNumber) {
    this.itemNumber = itemNumber;
  }

  public ActWebApiModelsProductsProduct price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * The price of the opportunity product.
   * @return price
  **/
  @ApiModelProperty(value = "The price of the opportunity product.")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsProductsProduct actWebApiModelsProductsProduct = (ActWebApiModelsProductsProduct) o;
    return Objects.equals(this.id, actWebApiModelsProductsProduct.id) &&
        Objects.equals(this.name, actWebApiModelsProductsProduct.name) &&
        Objects.equals(this.cost, actWebApiModelsProductsProduct.cost) &&
        Objects.equals(this.createDate, actWebApiModelsProductsProduct.createDate) &&
        Objects.equals(this.editDate, actWebApiModelsProductsProduct.editDate) &&
        Objects.equals(this.itemNumber, actWebApiModelsProductsProduct.itemNumber) &&
        Objects.equals(this.price, actWebApiModelsProductsProduct.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, cost, createDate, editDate, itemNumber, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsProductsProduct {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    editDate: ").append(toIndentedString(editDate)).append("\n");
    sb.append("    itemNumber: ").append(toIndentedString(itemNumber)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

