/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsActivitiesEmbededActivityContact {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("displayName")
  private String displayName = null;

  public ActWebApiModelsActivitiesEmbededActivityContact id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique identifier that represents the attendee.
   * @return id
  **/
  @ApiModelProperty(value = "A unique identifier that represents the attendee.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsActivitiesEmbededActivityContact displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The name of the attendee.
   * @return displayName
  **/
  @ApiModelProperty(value = "The name of the attendee.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsActivitiesEmbededActivityContact actWebApiModelsActivitiesEmbededActivityContact = (ActWebApiModelsActivitiesEmbededActivityContact) o;
    return Objects.equals(this.id, actWebApiModelsActivitiesEmbededActivityContact.id) &&
        Objects.equals(this.displayName, actWebApiModelsActivitiesEmbededActivityContact.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsActivitiesEmbededActivityContact {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

