/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The current process for a given opportunity.
 */
@ApiModel(description = "The current process for a given opportunity.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsOpportunitiesProcess {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  public ActWebApiModelsOpportunitiesProcess id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Gets the unique identifier of the stage.
   * @return id
  **/
  @ApiModelProperty(value = "Gets the unique identifier of the stage.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsOpportunitiesProcess name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Gets/Sets the name of the stage.
   * @return name
  **/
  @ApiModelProperty(value = "Gets/Sets the name of the stage.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsOpportunitiesProcess description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Gets/Sets the description of the stage.
   * @return description
  **/
  @ApiModelProperty(value = "Gets/Sets the description of the stage.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsOpportunitiesProcess actWebApiModelsOpportunitiesProcess = (ActWebApiModelsOpportunitiesProcess) o;
    return Objects.equals(this.id, actWebApiModelsOpportunitiesProcess.id) &&
        Objects.equals(this.name, actWebApiModelsOpportunitiesProcess.name) &&
        Objects.equals(this.description, actWebApiModelsOpportunitiesProcess.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsOpportunitiesProcess {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

