/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Sales revenue or revenues is income received from selling goods or services over a period of time.
 */
@ApiModel(description = "Sales revenue or revenues is income received from selling goods or services over a period of time.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsAnalyticsPeriodicRevenue {
  @JsonProperty("periodName")
  private String periodName = null;

  @JsonProperty("revenue")
  private Double revenue = null;

  @JsonProperty("cost")
  private Double cost = null;

  @JsonProperty("oppCount")
  private Integer oppCount = null;

  public ActWebApiModelsAnalyticsPeriodicRevenue periodName(String periodName) {
    this.periodName = periodName;
    return this;
  }

   /**
   * The name of a specific time interval.
   * @return periodName
  **/
  @ApiModelProperty(value = "The name of a specific time interval.")
  public String getPeriodName() {
    return periodName;
  }

  public void setPeriodName(String periodName) {
    this.periodName = periodName;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenue revenue(Double revenue) {
    this.revenue = revenue;
    return this;
  }

   /**
   * The income generated from sale of goods or services, or any other use of capital or assets, associated with the main operations of an organization before any costs or expenses are deducted.
   * @return revenue
  **/
  @ApiModelProperty(value = "The income generated from sale of goods or services, or any other use of capital or assets, associated with the main operations of an organization before any costs or expenses are deducted.")
  public Double getRevenue() {
    return revenue;
  }

  public void setRevenue(Double revenue) {
    this.revenue = revenue;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenue cost(Double cost) {
    this.cost = cost;
    return this;
  }

   /**
   * An amount that has to be paid or given up in order to get something.
   * @return cost
  **/
  @ApiModelProperty(value = "An amount that has to be paid or given up in order to get something.")
  public Double getCost() {
    return cost;
  }

  public void setCost(Double cost) {
    this.cost = cost;
  }

  public ActWebApiModelsAnalyticsPeriodicRevenue oppCount(Integer oppCount) {
    this.oppCount = oppCount;
    return this;
  }

   /**
   * Total count of opportunity produces assicated with the revenue.
   * @return oppCount
  **/
  @ApiModelProperty(value = "Total count of opportunity produces assicated with the revenue.")
  public Integer getOppCount() {
    return oppCount;
  }

  public void setOppCount(Integer oppCount) {
    this.oppCount = oppCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsAnalyticsPeriodicRevenue actWebApiModelsAnalyticsPeriodicRevenue = (ActWebApiModelsAnalyticsPeriodicRevenue) o;
    return Objects.equals(this.periodName, actWebApiModelsAnalyticsPeriodicRevenue.periodName) &&
        Objects.equals(this.revenue, actWebApiModelsAnalyticsPeriodicRevenue.revenue) &&
        Objects.equals(this.cost, actWebApiModelsAnalyticsPeriodicRevenue.cost) &&
        Objects.equals(this.oppCount, actWebApiModelsAnalyticsPeriodicRevenue.oppCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodName, revenue, cost, oppCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsAnalyticsPeriodicRevenue {\n");
    
    sb.append("    periodName: ").append(toIndentedString(periodName)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    oppCount: ").append(toIndentedString(oppCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

