/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.ActWebApiModelsAddress;
import com.act.client.swagger.model.SystemObject;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a group of ACT! entities.
 */
@ApiModel(description = "Represents a group of ACT! entities.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsGroupsGroup {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("parentID")
  private String parentID = null;

  @JsonProperty("heirarchyLevel")
  private Integer heirarchyLevel = null;

  @JsonProperty("address")
  private ActWebApiModelsAddress address = null;

  @JsonProperty("customFields")
  private Map<String, SystemObject> customFields = null;

  @JsonProperty("edited")
  private OffsetDateTime edited = null;

  @JsonProperty("editedBy")
  private String editedBy = null;

  @JsonProperty("recordOwner")
  private String recordOwner = null;

  public ActWebApiModelsGroupsGroup id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier (id) for a group.
   * @return id
  **/
  @ApiModelProperty(value = "The unique identifier (id) for a group.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsGroupsGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the group.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the group.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsGroupsGroup description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A brief written respresentation of a group.
   * @return description
  **/
  @ApiModelProperty(value = "A brief written respresentation of a group.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActWebApiModelsGroupsGroup created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * A timestamp when this group was created
   * @return created
  **/
  @ApiModelProperty(value = "A timestamp when this group was created")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public ActWebApiModelsGroupsGroup parentID(String parentID) {
    this.parentID = parentID;
    return this;
  }

   /**
   * The group&#39;s parent entity.
   * @return parentID
  **/
  @ApiModelProperty(value = "The group's parent entity.")
  public String getParentID() {
    return parentID;
  }

  public void setParentID(String parentID) {
    this.parentID = parentID;
  }

  public ActWebApiModelsGroupsGroup heirarchyLevel(Integer heirarchyLevel) {
    this.heirarchyLevel = heirarchyLevel;
    return this;
  }

   /**
   * The level this group appears in its hierarchy.
   * @return heirarchyLevel
  **/
  @ApiModelProperty(value = "The level this group appears in its hierarchy.")
  public Integer getHeirarchyLevel() {
    return heirarchyLevel;
  }

  public void setHeirarchyLevel(Integer heirarchyLevel) {
    this.heirarchyLevel = heirarchyLevel;
  }

  public ActWebApiModelsGroupsGroup address(ActWebApiModelsAddress address) {
    this.address = address;
    return this;
  }

   /**
   * The group address.
   * @return address
  **/
  @ApiModelProperty(value = "The group address.")
  public ActWebApiModelsAddress getAddress() {
    return address;
  }

  public void setAddress(ActWebApiModelsAddress address) {
    this.address = address;
  }

  public ActWebApiModelsGroupsGroup customFields(Map<String, SystemObject> customFields) {
    this.customFields = customFields;
    return this;
  }

  public ActWebApiModelsGroupsGroup putCustomFieldsItem(String key, SystemObject customFieldsItem) {
    if (this.customFields == null) {
      this.customFields = new HashMap<String, SystemObject>();
    }
    this.customFields.put(key, customFieldsItem);
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @ApiModelProperty(value = "")
  public Map<String, SystemObject> getCustomFields() {
    return customFields;
  }

  public void setCustomFields(Map<String, SystemObject> customFields) {
    this.customFields = customFields;
  }

  public ActWebApiModelsGroupsGroup edited(OffsetDateTime edited) {
    this.edited = edited;
    return this;
  }

   /**
   * Get edited
   * @return edited
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEdited() {
    return edited;
  }

  public void setEdited(OffsetDateTime edited) {
    this.edited = edited;
  }

  public ActWebApiModelsGroupsGroup editedBy(String editedBy) {
    this.editedBy = editedBy;
    return this;
  }

   /**
   * Get editedBy
   * @return editedBy
  **/
  @ApiModelProperty(value = "")
  public String getEditedBy() {
    return editedBy;
  }

  public void setEditedBy(String editedBy) {
    this.editedBy = editedBy;
  }

  public ActWebApiModelsGroupsGroup recordOwner(String recordOwner) {
    this.recordOwner = recordOwner;
    return this;
  }

   /**
   * Get recordOwner
   * @return recordOwner
  **/
  @ApiModelProperty(value = "")
  public String getRecordOwner() {
    return recordOwner;
  }

  public void setRecordOwner(String recordOwner) {
    this.recordOwner = recordOwner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsGroupsGroup actWebApiModelsGroupsGroup = (ActWebApiModelsGroupsGroup) o;
    return Objects.equals(this.id, actWebApiModelsGroupsGroup.id) &&
        Objects.equals(this.name, actWebApiModelsGroupsGroup.name) &&
        Objects.equals(this.description, actWebApiModelsGroupsGroup.description) &&
        Objects.equals(this.created, actWebApiModelsGroupsGroup.created) &&
        Objects.equals(this.parentID, actWebApiModelsGroupsGroup.parentID) &&
        Objects.equals(this.heirarchyLevel, actWebApiModelsGroupsGroup.heirarchyLevel) &&
        Objects.equals(this.address, actWebApiModelsGroupsGroup.address) &&
        Objects.equals(this.customFields, actWebApiModelsGroupsGroup.customFields) &&
        Objects.equals(this.edited, actWebApiModelsGroupsGroup.edited) &&
        Objects.equals(this.editedBy, actWebApiModelsGroupsGroup.editedBy) &&
        Objects.equals(this.recordOwner, actWebApiModelsGroupsGroup.recordOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, created, parentID, heirarchyLevel, address, customFields, edited, editedBy, recordOwner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsGroupsGroup {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    parentID: ").append(toIndentedString(parentID)).append("\n");
    sb.append("    heirarchyLevel: ").append(toIndentedString(heirarchyLevel)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    edited: ").append(toIndentedString(edited)).append("\n");
    sb.append("    editedBy: ").append(toIndentedString(editedBy)).append("\n");
    sb.append("    recordOwner: ").append(toIndentedString(recordOwner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

