/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.ActWebApiModelsMetaDataSchemaPickListInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * 
 */
@ApiModel(description = "")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class ActWebApiModelsMetaDataSchemaColumn {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("recordType")
  private String recordType = null;

  @JsonProperty("aliasName")
  private String aliasName = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("length")
  private Integer length = null;

  @JsonProperty("defaultValue")
  private String defaultValue = null;

  @JsonProperty("fieldFormat")
  private String fieldFormat = null;

  @JsonProperty("isAllowBlank")
  private Boolean isAllowBlank = null;

  @JsonProperty("isCustom")
  private Boolean isCustom = null;

  @JsonProperty("isNullable")
  private Boolean isNullable = null;

  @JsonProperty("isPrimary")
  private Boolean isPrimary = null;

  @JsonProperty("isReadOnly")
  private Boolean isReadOnly = null;

  @JsonProperty("isTracked")
  private Boolean isTracked = null;

  @JsonProperty("createDate")
  private OffsetDateTime createDate = null;

  @JsonProperty("editDate")
  private OffsetDateTime editDate = null;

  @JsonProperty("picklist")
  private ActWebApiModelsMetaDataSchemaPickListInfo picklist = null;

  public ActWebApiModelsMetaDataSchemaColumn id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ActWebApiModelsMetaDataSchemaColumn name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActWebApiModelsMetaDataSchemaColumn recordType(String recordType) {
    this.recordType = recordType;
    return this;
  }

   /**
   * 
   * @return recordType
  **/
  @ApiModelProperty(value = "")
  public String getRecordType() {
    return recordType;
  }

  public void setRecordType(String recordType) {
    this.recordType = recordType;
  }

  public ActWebApiModelsMetaDataSchemaColumn aliasName(String aliasName) {
    this.aliasName = aliasName;
    return this;
  }

   /**
   * 
   * @return aliasName
  **/
  @ApiModelProperty(value = "")
  public String getAliasName() {
    return aliasName;
  }

  public void setAliasName(String aliasName) {
    this.aliasName = aliasName;
  }

  public ActWebApiModelsMetaDataSchemaColumn displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * 
   * @return displayName
  **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ActWebApiModelsMetaDataSchemaColumn type(String type) {
    this.type = type;
    return this;
  }

   /**
   * 
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ActWebApiModelsMetaDataSchemaColumn length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * 
   * @return length
  **/
  @ApiModelProperty(value = "")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }

  public ActWebApiModelsMetaDataSchemaColumn defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * 
   * @return defaultValue
  **/
  @ApiModelProperty(value = "")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public ActWebApiModelsMetaDataSchemaColumn fieldFormat(String fieldFormat) {
    this.fieldFormat = fieldFormat;
    return this;
  }

   /**
   * 
   * @return fieldFormat
  **/
  @ApiModelProperty(value = "")
  public String getFieldFormat() {
    return fieldFormat;
  }

  public void setFieldFormat(String fieldFormat) {
    this.fieldFormat = fieldFormat;
  }

  public ActWebApiModelsMetaDataSchemaColumn isAllowBlank(Boolean isAllowBlank) {
    this.isAllowBlank = isAllowBlank;
    return this;
  }

   /**
   * 
   * @return isAllowBlank
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsAllowBlank() {
    return isAllowBlank;
  }

  public void setIsAllowBlank(Boolean isAllowBlank) {
    this.isAllowBlank = isAllowBlank;
  }

  public ActWebApiModelsMetaDataSchemaColumn isCustom(Boolean isCustom) {
    this.isCustom = isCustom;
    return this;
  }

   /**
   * 
   * @return isCustom
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsCustom() {
    return isCustom;
  }

  public void setIsCustom(Boolean isCustom) {
    this.isCustom = isCustom;
  }

  public ActWebApiModelsMetaDataSchemaColumn isNullable(Boolean isNullable) {
    this.isNullable = isNullable;
    return this;
  }

   /**
   * 
   * @return isNullable
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsNullable() {
    return isNullable;
  }

  public void setIsNullable(Boolean isNullable) {
    this.isNullable = isNullable;
  }

  public ActWebApiModelsMetaDataSchemaColumn isPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * 
   * @return isPrimary
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrimary() {
    return isPrimary;
  }

  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }

  public ActWebApiModelsMetaDataSchemaColumn isReadOnly(Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
    return this;
  }

   /**
   * Indicates this field to be readonly
   * @return isReadOnly
  **/
  @ApiModelProperty(value = "Indicates this field to be readonly")
  public Boolean isIsReadOnly() {
    return isReadOnly;
  }

  public void setIsReadOnly(Boolean isReadOnly) {
    this.isReadOnly = isReadOnly;
  }

  public ActWebApiModelsMetaDataSchemaColumn isTracked(Boolean isTracked) {
    this.isTracked = isTracked;
    return this;
  }

   /**
   * 
   * @return isTracked
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsTracked() {
    return isTracked;
  }

  public void setIsTracked(Boolean isTracked) {
    this.isTracked = isTracked;
  }

  public ActWebApiModelsMetaDataSchemaColumn createDate(OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

   /**
   * 
   * @return createDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }

  public ActWebApiModelsMetaDataSchemaColumn editDate(OffsetDateTime editDate) {
    this.editDate = editDate;
    return this;
  }

   /**
   * 
   * @return editDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEditDate() {
    return editDate;
  }

  public void setEditDate(OffsetDateTime editDate) {
    this.editDate = editDate;
  }

  public ActWebApiModelsMetaDataSchemaColumn picklist(ActWebApiModelsMetaDataSchemaPickListInfo picklist) {
    this.picklist = picklist;
    return this;
  }

   /**
   * 
   * @return picklist
  **/
  @ApiModelProperty(value = "")
  public ActWebApiModelsMetaDataSchemaPickListInfo getPicklist() {
    return picklist;
  }

  public void setPicklist(ActWebApiModelsMetaDataSchemaPickListInfo picklist) {
    this.picklist = picklist;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActWebApiModelsMetaDataSchemaColumn actWebApiModelsMetaDataSchemaColumn = (ActWebApiModelsMetaDataSchemaColumn) o;
    return Objects.equals(this.id, actWebApiModelsMetaDataSchemaColumn.id) &&
        Objects.equals(this.name, actWebApiModelsMetaDataSchemaColumn.name) &&
        Objects.equals(this.recordType, actWebApiModelsMetaDataSchemaColumn.recordType) &&
        Objects.equals(this.aliasName, actWebApiModelsMetaDataSchemaColumn.aliasName) &&
        Objects.equals(this.displayName, actWebApiModelsMetaDataSchemaColumn.displayName) &&
        Objects.equals(this.type, actWebApiModelsMetaDataSchemaColumn.type) &&
        Objects.equals(this.length, actWebApiModelsMetaDataSchemaColumn.length) &&
        Objects.equals(this.defaultValue, actWebApiModelsMetaDataSchemaColumn.defaultValue) &&
        Objects.equals(this.fieldFormat, actWebApiModelsMetaDataSchemaColumn.fieldFormat) &&
        Objects.equals(this.isAllowBlank, actWebApiModelsMetaDataSchemaColumn.isAllowBlank) &&
        Objects.equals(this.isCustom, actWebApiModelsMetaDataSchemaColumn.isCustom) &&
        Objects.equals(this.isNullable, actWebApiModelsMetaDataSchemaColumn.isNullable) &&
        Objects.equals(this.isPrimary, actWebApiModelsMetaDataSchemaColumn.isPrimary) &&
        Objects.equals(this.isReadOnly, actWebApiModelsMetaDataSchemaColumn.isReadOnly) &&
        Objects.equals(this.isTracked, actWebApiModelsMetaDataSchemaColumn.isTracked) &&
        Objects.equals(this.createDate, actWebApiModelsMetaDataSchemaColumn.createDate) &&
        Objects.equals(this.editDate, actWebApiModelsMetaDataSchemaColumn.editDate) &&
        Objects.equals(this.picklist, actWebApiModelsMetaDataSchemaColumn.picklist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, recordType, aliasName, displayName, type, length, defaultValue, fieldFormat, isAllowBlank, isCustom, isNullable, isPrimary, isReadOnly, isTracked, createDate, editDate, picklist);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActWebApiModelsMetaDataSchemaColumn {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    recordType: ").append(toIndentedString(recordType)).append("\n");
    sb.append("    aliasName: ").append(toIndentedString(aliasName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    fieldFormat: ").append(toIndentedString(fieldFormat)).append("\n");
    sb.append("    isAllowBlank: ").append(toIndentedString(isAllowBlank)).append("\n");
    sb.append("    isCustom: ").append(toIndentedString(isCustom)).append("\n");
    sb.append("    isNullable: ").append(toIndentedString(isNullable)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    isReadOnly: ").append(toIndentedString(isReadOnly)).append("\n");
    sb.append("    isTracked: ").append(toIndentedString(isTracked)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    editDate: ").append(toIndentedString(editDate)).append("\n");
    sb.append("    picklist: ").append(toIndentedString(picklist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

