/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmProperty;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmStructuredType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MicrosoftODataEdmIEdmStructuredType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmStructuredType {
  @JsonProperty("isAbstract")
  private Boolean isAbstract = null;

  @JsonProperty("isOpen")
  private Boolean isOpen = null;

  @JsonProperty("baseType")
  private MicrosoftODataEdmIEdmStructuredType baseType = null;

  @JsonProperty("declaredProperties")
  private List<MicrosoftODataEdmIEdmProperty> declaredProperties = null;

  /**
   * Gets or Sets typeKind
   */
  public enum TypeKindEnum {
    NONE("None"),
    
    PRIMITIVE("Primitive"),
    
    ENTITY("Entity"),
    
    COMPLEX("Complex"),
    
    COLLECTION("Collection"),
    
    ENTITYREFERENCE("EntityReference"),
    
    ENUM("Enum"),
    
    TYPEDEFINITION("TypeDefinition");

    private String value;

    TypeKindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeKindEnum fromValue(String text) {
      for (TypeKindEnum b : TypeKindEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("typeKind")
  private TypeKindEnum typeKind = null;

   /**
   * Get isAbstract
   * @return isAbstract
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsAbstract() {
    return isAbstract;
  }

   /**
   * Get isOpen
   * @return isOpen
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsOpen() {
    return isOpen;
  }

  public MicrosoftODataEdmIEdmStructuredType baseType(MicrosoftODataEdmIEdmStructuredType baseType) {
    this.baseType = baseType;
    return this;
  }

   /**
   * Get baseType
   * @return baseType
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmStructuredType getBaseType() {
    return baseType;
  }

  public void setBaseType(MicrosoftODataEdmIEdmStructuredType baseType) {
    this.baseType = baseType;
  }

  public MicrosoftODataEdmIEdmStructuredType declaredProperties(List<MicrosoftODataEdmIEdmProperty> declaredProperties) {
    this.declaredProperties = declaredProperties;
    return this;
  }

  public MicrosoftODataEdmIEdmStructuredType addDeclaredPropertiesItem(MicrosoftODataEdmIEdmProperty declaredPropertiesItem) {
    if (this.declaredProperties == null) {
      this.declaredProperties = new ArrayList<MicrosoftODataEdmIEdmProperty>();
    }
    this.declaredProperties.add(declaredPropertiesItem);
    return this;
  }

   /**
   * Get declaredProperties
   * @return declaredProperties
  **/
  @ApiModelProperty(value = "")
  public List<MicrosoftODataEdmIEdmProperty> getDeclaredProperties() {
    return declaredProperties;
  }

  public void setDeclaredProperties(List<MicrosoftODataEdmIEdmProperty> declaredProperties) {
    this.declaredProperties = declaredProperties;
  }

   /**
   * Get typeKind
   * @return typeKind
  **/
  @ApiModelProperty(value = "")
  public TypeKindEnum getTypeKind() {
    return typeKind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmStructuredType microsoftODataEdmIEdmStructuredType = (MicrosoftODataEdmIEdmStructuredType) o;
    return Objects.equals(this.isAbstract, microsoftODataEdmIEdmStructuredType.isAbstract) &&
        Objects.equals(this.isOpen, microsoftODataEdmIEdmStructuredType.isOpen) &&
        Objects.equals(this.baseType, microsoftODataEdmIEdmStructuredType.baseType) &&
        Objects.equals(this.declaredProperties, microsoftODataEdmIEdmStructuredType.declaredProperties) &&
        Objects.equals(this.typeKind, microsoftODataEdmIEdmStructuredType.typeKind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isAbstract, isOpen, baseType, declaredProperties, typeKind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmStructuredType {\n");
    
    sb.append("    isAbstract: ").append(toIndentedString(isAbstract)).append("\n");
    sb.append("    isOpen: ").append(toIndentedString(isOpen)).append("\n");
    sb.append("    baseType: ").append(toIndentedString(baseType)).append("\n");
    sb.append("    declaredProperties: ").append(toIndentedString(declaredProperties)).append("\n");
    sb.append("    typeKind: ").append(toIndentedString(typeKind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

