/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmEdmReferentialConstraintPropertyPair;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MicrosoftODataEdmIEdmReferentialConstraint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmReferentialConstraint {
  @JsonProperty("propertyPairs")
  private List<MicrosoftODataEdmEdmReferentialConstraintPropertyPair> propertyPairs = null;

  public MicrosoftODataEdmIEdmReferentialConstraint propertyPairs(List<MicrosoftODataEdmEdmReferentialConstraintPropertyPair> propertyPairs) {
    this.propertyPairs = propertyPairs;
    return this;
  }

  public MicrosoftODataEdmIEdmReferentialConstraint addPropertyPairsItem(MicrosoftODataEdmEdmReferentialConstraintPropertyPair propertyPairsItem) {
    if (this.propertyPairs == null) {
      this.propertyPairs = new ArrayList<MicrosoftODataEdmEdmReferentialConstraintPropertyPair>();
    }
    this.propertyPairs.add(propertyPairsItem);
    return this;
  }

   /**
   * Get propertyPairs
   * @return propertyPairs
  **/
  @ApiModelProperty(value = "")
  public List<MicrosoftODataEdmEdmReferentialConstraintPropertyPair> getPropertyPairs() {
    return propertyPairs;
  }

  public void setPropertyPairs(List<MicrosoftODataEdmEdmReferentialConstraintPropertyPair> propertyPairs) {
    this.propertyPairs = propertyPairs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmReferentialConstraint microsoftODataEdmIEdmReferentialConstraint = (MicrosoftODataEdmIEdmReferentialConstraint) o;
    return Objects.equals(this.propertyPairs, microsoftODataEdmIEdmReferentialConstraint.propertyPairs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyPairs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmReferentialConstraint {\n");
    
    sb.append("    propertyPairs: ").append(toIndentedString(propertyPairs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

