/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmTypeReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MicrosoftODataCoreUriParserSemanticRangeVariable
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataCoreUriParserSemanticRangeVariable {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("typeReference")
  private MicrosoftODataEdmIEdmTypeReference typeReference = null;

  @JsonProperty("kind")
  private Integer kind = null;

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public MicrosoftODataCoreUriParserSemanticRangeVariable typeReference(MicrosoftODataEdmIEdmTypeReference typeReference) {
    this.typeReference = typeReference;
    return this;
  }

   /**
   * Get typeReference
   * @return typeReference
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmTypeReference getTypeReference() {
    return typeReference;
  }

  public void setTypeReference(MicrosoftODataEdmIEdmTypeReference typeReference) {
    this.typeReference = typeReference;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public Integer getKind() {
    return kind;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataCoreUriParserSemanticRangeVariable microsoftODataCoreUriParserSemanticRangeVariable = (MicrosoftODataCoreUriParserSemanticRangeVariable) o;
    return Objects.equals(this.name, microsoftODataCoreUriParserSemanticRangeVariable.name) &&
        Objects.equals(this.typeReference, microsoftODataCoreUriParserSemanticRangeVariable.typeReference) &&
        Objects.equals(this.kind, microsoftODataCoreUriParserSemanticRangeVariable.kind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, typeReference, kind);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataCoreUriParserSemanticRangeVariable {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    typeReference: ").append(toIndentedString(typeReference)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

