/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmEntityContainer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MicrosoftODataEdmIEdmEntityContainerElement
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmEntityContainerElement {
  /**
   * Gets or Sets containerElementKind
   */
  public enum ContainerElementKindEnum {
    NONE("None"),
    
    ENTITYSET("EntitySet"),
    
    ACTIONIMPORT("ActionImport"),
    
    FUNCTIONIMPORT("FunctionImport"),
    
    SINGLETON("Singleton");

    private String value;

    ContainerElementKindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContainerElementKindEnum fromValue(String text) {
      for (ContainerElementKindEnum b : ContainerElementKindEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("containerElementKind")
  private ContainerElementKindEnum containerElementKind = null;

  @JsonProperty("container")
  private MicrosoftODataEdmIEdmEntityContainer container = null;

  @JsonProperty("name")
  private String name = null;

   /**
   * Get containerElementKind
   * @return containerElementKind
  **/
  @ApiModelProperty(value = "")
  public ContainerElementKindEnum getContainerElementKind() {
    return containerElementKind;
  }

  public MicrosoftODataEdmIEdmEntityContainerElement container(MicrosoftODataEdmIEdmEntityContainer container) {
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmEntityContainer getContainer() {
    return container;
  }

  public void setContainer(MicrosoftODataEdmIEdmEntityContainer container) {
    this.container = container;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmEntityContainerElement microsoftODataEdmIEdmEntityContainerElement = (MicrosoftODataEdmIEdmEntityContainerElement) o;
    return Objects.equals(this.containerElementKind, microsoftODataEdmIEdmEntityContainerElement.containerElementKind) &&
        Objects.equals(this.container, microsoftODataEdmIEdmEntityContainerElement.container) &&
        Objects.equals(this.name, microsoftODataEdmIEdmEntityContainerElement.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerElementKind, container, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmEntityContainerElement {\n");
    
    sb.append("    containerElementKind: ").append(toIndentedString(containerElementKind)).append("\n");
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

