/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmType;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MicrosoftODataEdmIEdmTypeReference
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmTypeReference {
  @JsonProperty("isNullable")
  private Boolean isNullable = null;

  @JsonProperty("definition")
  private MicrosoftODataEdmIEdmType definition = null;

   /**
   * Get isNullable
   * @return isNullable
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsNullable() {
    return isNullable;
  }

  public MicrosoftODataEdmIEdmTypeReference definition(MicrosoftODataEdmIEdmType definition) {
    this.definition = definition;
    return this;
  }

   /**
   * Get definition
   * @return definition
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmType getDefinition() {
    return definition;
  }

  public void setDefinition(MicrosoftODataEdmIEdmType definition) {
    this.definition = definition;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmTypeReference microsoftODataEdmIEdmTypeReference = (MicrosoftODataEdmIEdmTypeReference) o;
    return Objects.equals(this.isNullable, microsoftODataEdmIEdmTypeReference.isNullable) &&
        Objects.equals(this.definition, microsoftODataEdmIEdmTypeReference.definition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isNullable, definition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmTypeReference {\n");
    
    sb.append("    isNullable: ").append(toIndentedString(isNullable)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

