/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmNavigationProperty;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmNavigationSource;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MicrosoftODataEdmIEdmNavigationPropertyBinding
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmNavigationPropertyBinding {
  @JsonProperty("navigationProperty")
  private MicrosoftODataEdmIEdmNavigationProperty navigationProperty = null;

  @JsonProperty("target")
  private MicrosoftODataEdmIEdmNavigationSource target = null;

  public MicrosoftODataEdmIEdmNavigationPropertyBinding navigationProperty(MicrosoftODataEdmIEdmNavigationProperty navigationProperty) {
    this.navigationProperty = navigationProperty;
    return this;
  }

   /**
   * Get navigationProperty
   * @return navigationProperty
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmNavigationProperty getNavigationProperty() {
    return navigationProperty;
  }

  public void setNavigationProperty(MicrosoftODataEdmIEdmNavigationProperty navigationProperty) {
    this.navigationProperty = navigationProperty;
  }

  public MicrosoftODataEdmIEdmNavigationPropertyBinding target(MicrosoftODataEdmIEdmNavigationSource target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmNavigationSource getTarget() {
    return target;
  }

  public void setTarget(MicrosoftODataEdmIEdmNavigationSource target) {
    this.target = target;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmNavigationPropertyBinding microsoftODataEdmIEdmNavigationPropertyBinding = (MicrosoftODataEdmIEdmNavigationPropertyBinding) o;
    return Objects.equals(this.navigationProperty, microsoftODataEdmIEdmNavigationPropertyBinding.navigationProperty) &&
        Objects.equals(this.target, microsoftODataEdmIEdmNavigationPropertyBinding.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(navigationProperty, target);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmNavigationPropertyBinding {\n");
    
    sb.append("    navigationProperty: ").append(toIndentedString(navigationProperty)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

