/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataEdmAnnotationsIEdmDirectValueAnnotationsManager;
import com.act.client.swagger.model.MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmEntityContainer;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmModel;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmSchemaElement;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * MicrosoftODataEdmIEdmModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataEdmIEdmModel {
  @JsonProperty("schemaElements")
  private List<MicrosoftODataEdmIEdmSchemaElement> schemaElements = null;

  @JsonProperty("vocabularyAnnotations")
  private List<MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation> vocabularyAnnotations = null;

  @JsonProperty("referencedModels")
  private List<MicrosoftODataEdmIEdmModel> referencedModels = null;

  @JsonProperty("declaredNamespaces")
  private List<String> declaredNamespaces = null;

  @JsonProperty("directValueAnnotationsManager")
  private MicrosoftODataEdmAnnotationsIEdmDirectValueAnnotationsManager directValueAnnotationsManager = null;

  @JsonProperty("entityContainer")
  private MicrosoftODataEdmIEdmEntityContainer entityContainer = null;

  public MicrosoftODataEdmIEdmModel schemaElements(List<MicrosoftODataEdmIEdmSchemaElement> schemaElements) {
    this.schemaElements = schemaElements;
    return this;
  }

  public MicrosoftODataEdmIEdmModel addSchemaElementsItem(MicrosoftODataEdmIEdmSchemaElement schemaElementsItem) {
    if (this.schemaElements == null) {
      this.schemaElements = new ArrayList<MicrosoftODataEdmIEdmSchemaElement>();
    }
    this.schemaElements.add(schemaElementsItem);
    return this;
  }

   /**
   * Get schemaElements
   * @return schemaElements
  **/
  @ApiModelProperty(value = "")
  public List<MicrosoftODataEdmIEdmSchemaElement> getSchemaElements() {
    return schemaElements;
  }

  public void setSchemaElements(List<MicrosoftODataEdmIEdmSchemaElement> schemaElements) {
    this.schemaElements = schemaElements;
  }

  public MicrosoftODataEdmIEdmModel vocabularyAnnotations(List<MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation> vocabularyAnnotations) {
    this.vocabularyAnnotations = vocabularyAnnotations;
    return this;
  }

  public MicrosoftODataEdmIEdmModel addVocabularyAnnotationsItem(MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation vocabularyAnnotationsItem) {
    if (this.vocabularyAnnotations == null) {
      this.vocabularyAnnotations = new ArrayList<MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation>();
    }
    this.vocabularyAnnotations.add(vocabularyAnnotationsItem);
    return this;
  }

   /**
   * Get vocabularyAnnotations
   * @return vocabularyAnnotations
  **/
  @ApiModelProperty(value = "")
  public List<MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation> getVocabularyAnnotations() {
    return vocabularyAnnotations;
  }

  public void setVocabularyAnnotations(List<MicrosoftODataEdmAnnotationsIEdmVocabularyAnnotation> vocabularyAnnotations) {
    this.vocabularyAnnotations = vocabularyAnnotations;
  }

  public MicrosoftODataEdmIEdmModel referencedModels(List<MicrosoftODataEdmIEdmModel> referencedModels) {
    this.referencedModels = referencedModels;
    return this;
  }

  public MicrosoftODataEdmIEdmModel addReferencedModelsItem(MicrosoftODataEdmIEdmModel referencedModelsItem) {
    if (this.referencedModels == null) {
      this.referencedModels = new ArrayList<MicrosoftODataEdmIEdmModel>();
    }
    this.referencedModels.add(referencedModelsItem);
    return this;
  }

   /**
   * Get referencedModels
   * @return referencedModels
  **/
  @ApiModelProperty(value = "")
  public List<MicrosoftODataEdmIEdmModel> getReferencedModels() {
    return referencedModels;
  }

  public void setReferencedModels(List<MicrosoftODataEdmIEdmModel> referencedModels) {
    this.referencedModels = referencedModels;
  }

  public MicrosoftODataEdmIEdmModel declaredNamespaces(List<String> declaredNamespaces) {
    this.declaredNamespaces = declaredNamespaces;
    return this;
  }

  public MicrosoftODataEdmIEdmModel addDeclaredNamespacesItem(String declaredNamespacesItem) {
    if (this.declaredNamespaces == null) {
      this.declaredNamespaces = new ArrayList<String>();
    }
    this.declaredNamespaces.add(declaredNamespacesItem);
    return this;
  }

   /**
   * Get declaredNamespaces
   * @return declaredNamespaces
  **/
  @ApiModelProperty(value = "")
  public List<String> getDeclaredNamespaces() {
    return declaredNamespaces;
  }

  public void setDeclaredNamespaces(List<String> declaredNamespaces) {
    this.declaredNamespaces = declaredNamespaces;
  }

  public MicrosoftODataEdmIEdmModel directValueAnnotationsManager(MicrosoftODataEdmAnnotationsIEdmDirectValueAnnotationsManager directValueAnnotationsManager) {
    this.directValueAnnotationsManager = directValueAnnotationsManager;
    return this;
  }

   /**
   * Get directValueAnnotationsManager
   * @return directValueAnnotationsManager
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmAnnotationsIEdmDirectValueAnnotationsManager getDirectValueAnnotationsManager() {
    return directValueAnnotationsManager;
  }

  public void setDirectValueAnnotationsManager(MicrosoftODataEdmAnnotationsIEdmDirectValueAnnotationsManager directValueAnnotationsManager) {
    this.directValueAnnotationsManager = directValueAnnotationsManager;
  }

  public MicrosoftODataEdmIEdmModel entityContainer(MicrosoftODataEdmIEdmEntityContainer entityContainer) {
    this.entityContainer = entityContainer;
    return this;
  }

   /**
   * Get entityContainer
   * @return entityContainer
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmEntityContainer getEntityContainer() {
    return entityContainer;
  }

  public void setEntityContainer(MicrosoftODataEdmIEdmEntityContainer entityContainer) {
    this.entityContainer = entityContainer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataEdmIEdmModel microsoftODataEdmIEdmModel = (MicrosoftODataEdmIEdmModel) o;
    return Objects.equals(this.schemaElements, microsoftODataEdmIEdmModel.schemaElements) &&
        Objects.equals(this.vocabularyAnnotations, microsoftODataEdmIEdmModel.vocabularyAnnotations) &&
        Objects.equals(this.referencedModels, microsoftODataEdmIEdmModel.referencedModels) &&
        Objects.equals(this.declaredNamespaces, microsoftODataEdmIEdmModel.declaredNamespaces) &&
        Objects.equals(this.directValueAnnotationsManager, microsoftODataEdmIEdmModel.directValueAnnotationsManager) &&
        Objects.equals(this.entityContainer, microsoftODataEdmIEdmModel.entityContainer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(schemaElements, vocabularyAnnotations, referencedModels, declaredNamespaces, directValueAnnotationsManager, entityContainer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataEdmIEdmModel {\n");
    
    sb.append("    schemaElements: ").append(toIndentedString(schemaElements)).append("\n");
    sb.append("    vocabularyAnnotations: ").append(toIndentedString(vocabularyAnnotations)).append("\n");
    sb.append("    referencedModels: ").append(toIndentedString(referencedModels)).append("\n");
    sb.append("    declaredNamespaces: ").append(toIndentedString(declaredNamespaces)).append("\n");
    sb.append("    directValueAnnotationsManager: ").append(toIndentedString(directValueAnnotationsManager)).append("\n");
    sb.append("    entityContainer: ").append(toIndentedString(entityContainer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

