/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataCoreUriParserSemanticRangeVariable;
import com.act.client.swagger.model.MicrosoftODataCoreUriParserSemanticSingleValueNode;
import com.act.client.swagger.model.MicrosoftODataEdmIEdmTypeReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MicrosoftODataCoreUriParserSemanticFilterClause
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class MicrosoftODataCoreUriParserSemanticFilterClause {
  @JsonProperty("expression")
  private MicrosoftODataCoreUriParserSemanticSingleValueNode expression = null;

  @JsonProperty("rangeVariable")
  private MicrosoftODataCoreUriParserSemanticRangeVariable rangeVariable = null;

  @JsonProperty("itemType")
  private MicrosoftODataEdmIEdmTypeReference itemType = null;

  public MicrosoftODataCoreUriParserSemanticFilterClause expression(MicrosoftODataCoreUriParserSemanticSingleValueNode expression) {
    this.expression = expression;
    return this;
  }

   /**
   * Get expression
   * @return expression
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataCoreUriParserSemanticSingleValueNode getExpression() {
    return expression;
  }

  public void setExpression(MicrosoftODataCoreUriParserSemanticSingleValueNode expression) {
    this.expression = expression;
  }

  public MicrosoftODataCoreUriParserSemanticFilterClause rangeVariable(MicrosoftODataCoreUriParserSemanticRangeVariable rangeVariable) {
    this.rangeVariable = rangeVariable;
    return this;
  }

   /**
   * Get rangeVariable
   * @return rangeVariable
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataCoreUriParserSemanticRangeVariable getRangeVariable() {
    return rangeVariable;
  }

  public void setRangeVariable(MicrosoftODataCoreUriParserSemanticRangeVariable rangeVariable) {
    this.rangeVariable = rangeVariable;
  }

  public MicrosoftODataCoreUriParserSemanticFilterClause itemType(MicrosoftODataEdmIEdmTypeReference itemType) {
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataEdmIEdmTypeReference getItemType() {
    return itemType;
  }

  public void setItemType(MicrosoftODataEdmIEdmTypeReference itemType) {
    this.itemType = itemType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftODataCoreUriParserSemanticFilterClause microsoftODataCoreUriParserSemanticFilterClause = (MicrosoftODataCoreUriParserSemanticFilterClause) o;
    return Objects.equals(this.expression, microsoftODataCoreUriParserSemanticFilterClause.expression) &&
        Objects.equals(this.rangeVariable, microsoftODataCoreUriParserSemanticFilterClause.rangeVariable) &&
        Objects.equals(this.itemType, microsoftODataCoreUriParserSemanticFilterClause.itemType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expression, rangeVariable, itemType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftODataCoreUriParserSemanticFilterClause {\n");
    
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    rangeVariable: ").append(toIndentedString(rangeVariable)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

