/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.SystemWebODataODataQueryContext;
import com.act.client.swagger.model.SystemWebODataQueryValidatorsCountQueryValidator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SystemWebODataQueryCountQueryOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class SystemWebODataQueryCountQueryOption {
  @JsonProperty("context")
  private SystemWebODataODataQueryContext context = null;

  @JsonProperty("rawValue")
  private String rawValue = null;

  @JsonProperty("value")
  private Boolean value = null;

  @JsonProperty("validator")
  private SystemWebODataQueryValidatorsCountQueryValidator validator = null;

  public SystemWebODataQueryCountQueryOption context(SystemWebODataODataQueryContext context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataODataQueryContext getContext() {
    return context;
  }

  public void setContext(SystemWebODataODataQueryContext context) {
    this.context = context;
  }

   /**
   * Get rawValue
   * @return rawValue
  **/
  @ApiModelProperty(value = "")
  public String getRawValue() {
    return rawValue;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public Boolean isValue() {
    return value;
  }

  public SystemWebODataQueryCountQueryOption validator(SystemWebODataQueryValidatorsCountQueryValidator validator) {
    this.validator = validator;
    return this;
  }

   /**
   * Get validator
   * @return validator
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataQueryValidatorsCountQueryValidator getValidator() {
    return validator;
  }

  public void setValidator(SystemWebODataQueryValidatorsCountQueryValidator validator) {
    this.validator = validator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemWebODataQueryCountQueryOption systemWebODataQueryCountQueryOption = (SystemWebODataQueryCountQueryOption) o;
    return Objects.equals(this.context, systemWebODataQueryCountQueryOption.context) &&
        Objects.equals(this.rawValue, systemWebODataQueryCountQueryOption.rawValue) &&
        Objects.equals(this.value, systemWebODataQueryCountQueryOption.value) &&
        Objects.equals(this.validator, systemWebODataQueryCountQueryOption.validator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, rawValue, value, validator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemWebODataQueryCountQueryOption {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    rawValue: ").append(toIndentedString(rawValue)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    validator: ").append(toIndentedString(validator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

