/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataCoreUriParserSemanticFilterClause;
import com.act.client.swagger.model.SystemWebODataODataQueryContext;
import com.act.client.swagger.model.SystemWebODataQueryValidatorsFilterQueryValidator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SystemWebODataQueryFilterQueryOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class SystemWebODataQueryFilterQueryOption {
  @JsonProperty("context")
  private SystemWebODataODataQueryContext context = null;

  @JsonProperty("validator")
  private SystemWebODataQueryValidatorsFilterQueryValidator validator = null;

  @JsonProperty("filterClause")
  private MicrosoftODataCoreUriParserSemanticFilterClause filterClause = null;

  @JsonProperty("rawValue")
  private String rawValue = null;

  public SystemWebODataQueryFilterQueryOption context(SystemWebODataODataQueryContext context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataODataQueryContext getContext() {
    return context;
  }

  public void setContext(SystemWebODataODataQueryContext context) {
    this.context = context;
  }

  public SystemWebODataQueryFilterQueryOption validator(SystemWebODataQueryValidatorsFilterQueryValidator validator) {
    this.validator = validator;
    return this;
  }

   /**
   * Get validator
   * @return validator
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataQueryValidatorsFilterQueryValidator getValidator() {
    return validator;
  }

  public void setValidator(SystemWebODataQueryValidatorsFilterQueryValidator validator) {
    this.validator = validator;
  }

  public SystemWebODataQueryFilterQueryOption filterClause(MicrosoftODataCoreUriParserSemanticFilterClause filterClause) {
    this.filterClause = filterClause;
    return this;
  }

   /**
   * Get filterClause
   * @return filterClause
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataCoreUriParserSemanticFilterClause getFilterClause() {
    return filterClause;
  }

  public void setFilterClause(MicrosoftODataCoreUriParserSemanticFilterClause filterClause) {
    this.filterClause = filterClause;
  }

   /**
   * Get rawValue
   * @return rawValue
  **/
  @ApiModelProperty(value = "")
  public String getRawValue() {
    return rawValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemWebODataQueryFilterQueryOption systemWebODataQueryFilterQueryOption = (SystemWebODataQueryFilterQueryOption) o;
    return Objects.equals(this.context, systemWebODataQueryFilterQueryOption.context) &&
        Objects.equals(this.validator, systemWebODataQueryFilterQueryOption.validator) &&
        Objects.equals(this.filterClause, systemWebODataQueryFilterQueryOption.filterClause) &&
        Objects.equals(this.rawValue, systemWebODataQueryFilterQueryOption.rawValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, validator, filterClause, rawValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemWebODataQueryFilterQueryOption {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    validator: ").append(toIndentedString(validator)).append("\n");
    sb.append("    filterClause: ").append(toIndentedString(filterClause)).append("\n");
    sb.append("    rawValue: ").append(toIndentedString(rawValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

