/*
 * act.web.api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.act.client.swagger.model;

import java.util.Objects;
import com.act.client.swagger.model.MicrosoftODataCoreUriParserSemanticSelectExpandClause;
import com.act.client.swagger.model.SystemWebODataODataQueryContext;
import com.act.client.swagger.model.SystemWebODataQueryValidatorsSelectExpandQueryValidator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SystemWebODataQuerySelectExpandQueryOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-23T12:00:13.972Z")
public class SystemWebODataQuerySelectExpandQueryOption {
  @JsonProperty("context")
  private SystemWebODataODataQueryContext context = null;

  @JsonProperty("rawSelect")
  private String rawSelect = null;

  @JsonProperty("rawExpand")
  private String rawExpand = null;

  @JsonProperty("validator")
  private SystemWebODataQueryValidatorsSelectExpandQueryValidator validator = null;

  @JsonProperty("selectExpandClause")
  private MicrosoftODataCoreUriParserSemanticSelectExpandClause selectExpandClause = null;

  @JsonProperty("levelsMaxLiteralExpansionDepth")
  private Integer levelsMaxLiteralExpansionDepth = null;

  public SystemWebODataQuerySelectExpandQueryOption context(SystemWebODataODataQueryContext context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataODataQueryContext getContext() {
    return context;
  }

  public void setContext(SystemWebODataODataQueryContext context) {
    this.context = context;
  }

   /**
   * Get rawSelect
   * @return rawSelect
  **/
  @ApiModelProperty(value = "")
  public String getRawSelect() {
    return rawSelect;
  }

   /**
   * Get rawExpand
   * @return rawExpand
  **/
  @ApiModelProperty(value = "")
  public String getRawExpand() {
    return rawExpand;
  }

  public SystemWebODataQuerySelectExpandQueryOption validator(SystemWebODataQueryValidatorsSelectExpandQueryValidator validator) {
    this.validator = validator;
    return this;
  }

   /**
   * Get validator
   * @return validator
  **/
  @ApiModelProperty(value = "")
  public SystemWebODataQueryValidatorsSelectExpandQueryValidator getValidator() {
    return validator;
  }

  public void setValidator(SystemWebODataQueryValidatorsSelectExpandQueryValidator validator) {
    this.validator = validator;
  }

  public SystemWebODataQuerySelectExpandQueryOption selectExpandClause(MicrosoftODataCoreUriParserSemanticSelectExpandClause selectExpandClause) {
    this.selectExpandClause = selectExpandClause;
    return this;
  }

   /**
   * Get selectExpandClause
   * @return selectExpandClause
  **/
  @ApiModelProperty(value = "")
  public MicrosoftODataCoreUriParserSemanticSelectExpandClause getSelectExpandClause() {
    return selectExpandClause;
  }

  public void setSelectExpandClause(MicrosoftODataCoreUriParserSemanticSelectExpandClause selectExpandClause) {
    this.selectExpandClause = selectExpandClause;
  }

  public SystemWebODataQuerySelectExpandQueryOption levelsMaxLiteralExpansionDepth(Integer levelsMaxLiteralExpansionDepth) {
    this.levelsMaxLiteralExpansionDepth = levelsMaxLiteralExpansionDepth;
    return this;
  }

   /**
   * Get levelsMaxLiteralExpansionDepth
   * @return levelsMaxLiteralExpansionDepth
  **/
  @ApiModelProperty(value = "")
  public Integer getLevelsMaxLiteralExpansionDepth() {
    return levelsMaxLiteralExpansionDepth;
  }

  public void setLevelsMaxLiteralExpansionDepth(Integer levelsMaxLiteralExpansionDepth) {
    this.levelsMaxLiteralExpansionDepth = levelsMaxLiteralExpansionDepth;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemWebODataQuerySelectExpandQueryOption systemWebODataQuerySelectExpandQueryOption = (SystemWebODataQuerySelectExpandQueryOption) o;
    return Objects.equals(this.context, systemWebODataQuerySelectExpandQueryOption.context) &&
        Objects.equals(this.rawSelect, systemWebODataQuerySelectExpandQueryOption.rawSelect) &&
        Objects.equals(this.rawExpand, systemWebODataQuerySelectExpandQueryOption.rawExpand) &&
        Objects.equals(this.validator, systemWebODataQuerySelectExpandQueryOption.validator) &&
        Objects.equals(this.selectExpandClause, systemWebODataQuerySelectExpandQueryOption.selectExpandClause) &&
        Objects.equals(this.levelsMaxLiteralExpansionDepth, systemWebODataQuerySelectExpandQueryOption.levelsMaxLiteralExpansionDepth);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, rawSelect, rawExpand, validator, selectExpandClause, levelsMaxLiteralExpansionDepth);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemWebODataQuerySelectExpandQueryOption {\n");
    
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    rawSelect: ").append(toIndentedString(rawSelect)).append("\n");
    sb.append("    rawExpand: ").append(toIndentedString(rawExpand)).append("\n");
    sb.append("    validator: ").append(toIndentedString(validator)).append("\n");
    sb.append("    selectExpandClause: ").append(toIndentedString(selectExpandClause)).append("\n");
    sb.append("    levelsMaxLiteralExpansionDepth: ").append(toIndentedString(levelsMaxLiteralExpansionDepth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

